name: 'Setup npm publish action'
description: 'Setup npm and git for publishing to npm registry'
inputs:
  email:
    description: "Email to use in lerna commits"
    required: false
    default: 'bot@setup-npm-publish-action'
  username:
    description: 'User  name to use in lerna commits'
    required: false
    default: 'Github Action'
runs:
  using: 'docker'
  image: 'Dockerfile'
