name: 'Setup npm publish action'
description: 'Setup npm and git for publishing to npm registry'
inputs:
  email:
    description: "Email to use with git"
    required: false
    default: 'bot@setup-npm-publish-action'
  username:
    description: 'Username to use with git'
    required: false
    default: 'Github Action'
runs:
  using: "composite"
  steps:
    - name: Setup npm publish action
      env:
        EMAIL: ${{ inputs.email }}
        USERNAME: ${{ inputs.username }}
        # Additionally accepts the env vars GIT_DEPLOY_KEY and AUTH_TOKEN_STRING
        # passed through from the workflow.
      shell: bash
      run: |
        #!/bin/bash
        
        set -euo pipefail
        
        # Validate input
        if [ -z "$GIT_DEPLOY_KEY" ]
        then
            echo "No GIT_DEPLOY_KEY environment variable set"
            exit 255
        fi
        
        # Setup authentication for npm and mark the file as non-changed
        
        if [ -n "$AUTH_TOKEN_STRING" ]
        then
            echo -e "$AUTH_TOKEN_STRING" >> .npmrc
            git update-index --assume-unchanged .npmrc
        fi
        
        # The script is run as root so we need to allow npm to execute scripts as root.
        echo "unsafe-perm = true" >> ~/.npmrc
        
        # Setup SSH keys so we can push commits and tags to master branch
        mkdir -p "$HOME/.ssh"
        ssh-keyscan -t rsa github.com > "$HOME/.ssh/known_hosts"
        echo "$GIT_DEPLOY_KEY" > "$HOME/.ssh/id_rsa"
        chmod 400 "$HOME/.ssh/id_rsa"
        
        # Setup git
        git config user.email "$EMAIL"
        git config user.name "$USERNAME"
        git config core.sshCommand "ssh -i ${HOME}/.ssh/id_rsa -o UserKnownHostsFile=${HOME}/.ssh/known_hosts"
        
        git remote set-url origin "git@github.com:$GITHUB_REPOSITORY.git"
