name: 'Setup npm publish action'
description: 'Setup npm and git for publishing to npm registry'
inputs:
  email:
    description: "Email to use with git"
    required: false
    default: 'bot@setup-npm-publish-action'
  username:
    description: 'Username to use with git'
    required: false
    default: 'Github Action'
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"
